Endpoint slices
k8sgateway/k8sgateway pull request #10290
Opened 2024-11-07 11:58 UTC by tkukushkin

# Description

Migration of Kubernetes endpoints discovery from Endpoints to EndpointSlices.

# Context

EndpointSlice is recommended replacement of Endpoints.

In some scenarios there are no Endpoints but there are EndpointSlices.

As Endpoints are automatically mirrored to EndpointSlices this change shouldn't break anything.

## Testing steps

We've been using gloo 1.17.4 with this patch for one month on cluster with 1500+ virtual services without any problems.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-11-07 12:43 UTC, nfuden commented
Thanks for the contribution! We have another in flight pr to add similar work with kubernetes gateway implementation so this is amazing timing!

2024-11-07 12:56 UTC, nfuden commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +			if eps.Namespace != spec.GetServiceNamespace() || eps.Labels["kubernetes.io/service-name"] != spec.GetServiceName() {
per https://github.com/solo-io/gloo/pull/10265/files#r1831363552 we can grab the constant

2024-11-07 12:56 UTC, nfuden commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +	addr := endpoint.Addresses[0] // https://github.com/kubernetes/kubernetes/issues/106267
Is this sufficient to not hit dupes?

2024-11-07 13:31 UTC, tkukushkin commented
> Thanks for the contribution! We have another in flight pr to add similar work with kubernetes gateway implementation so this is amazing timing!

I am not an expert in Go, especially about writing tests. So if anything, I wouldn't mind at all if someone continued this PR instead of me. Otherwise, I will try to finish it by myself, but it would be really nice if someone could recommend what tests to add/fix.

2024-11-07 13:31 UTC, tkukushkin commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +			if eps.Namespace != spec.GetServiceNamespace() || eps.Labels["kubernetes.io/service-name"] != spec.GetServiceName() {
Fixed

2024-11-07 16:46 UTC, jenshu commented on install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
> +  - ednpointslices
```suggestion
  - endpointslices
```

2024-11-07 16:46 UTC, nfuden commented on install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml
> +  - ednpointslices
```suggestion
  - endpointslices
```

2024-11-08 13:08 UTC, nfuden commented
Added @danehans and @jenshu to this as reviewers. Perhaps next week if someone has bandwidth we can also add the extra tests mentioned here https://github.com/solo-io/gloo/pull/10290#issuecomment-2462249798 if still needed :)

2024-11-12 00:41 UTC, danehans commented
@tkukushkin thanks for your interest in the project. I have https://github.com/solo-io/gloo/pull/10265 under review to replace Endpoints with EndpointSlice for creating Upstream endpoints. PTAL at my PR as it includes EndpointSlice address deduplication. This is how the PR accomplishes EndpointSlice address deduplication:

1. Create a map keyed by `endpointslices[].endpoints[].addresses[].address`.
2. Iterate through the "ready" Endpoints of each EndpointSlice for a Service.
3. Check the map for the keyed address. If the address does not exist, add it to the map and create the LB endpoint using the unique address. Otherwise, continue to the next address. See `projects/gateway2/krtcollections/endpoints.go` in my PR for additional details.

I'm happy to help you if you are interested in working on any other issues. As a new contributor, I suggest working on an issue labeled [Good First Issue](https://github.com/solo-io/gloo/labels/Good%20First%20Issue).

2024-11-12 06:22 UTC, tkukushkin commented
@danehans Hello! Thank you for your response.

I checked #10265 and I noticed changes specifically in project/gateway2. Could I ask if there are plans to migrate projects/gloo/pkg/plugins/kubernetes/eds.go to use EndpointSlice as well? If not, would you mind sharing the reason behind closing this PR? I apologize if I'm missing some context here.

Additionally, I believe I may have already included some deduplication — not for the addresses (since they're deduplicated as map keys) but rather for the upstream references stored as map values. However, it's possible I overlooked something.

2024-11-12 18:32 UTC, danehans commented
@tkukushkin I apologize for closing this PR. I thought it was trying to fix the same issue as https://github.com/solo-io/gloo/pull/10265.

2024-11-12 19:46 UTC, danehans requested changes
A test case for Endpoint deduplication across multiple EndpointSlices of a Service is needed.

2024-11-12 19:46 UTC, danehans commented on projects/gloo/pkg/plugins/kubernetes/eds_test.go
> +				[]*discoveryv1.EndpointSlice{
Can you add a test similar to [this](https://github.com/solo-io/gloo/blob/main/projects/gateway2/krtcollections/endpoints_test.go#L567-L718) that asserts the deduplication of endpoints across multiple endpointslices?

2024-11-12 19:46 UTC, danehans commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +	addr := endpoint.Addresses[0] // https://github.com/kubernetes/kubernetes/issues/106267
See https://github.com/solo-io/gloo/pull/10265 for how EPS dedupe is implemented for kubeGateway.

2024-11-14 16:27 UTC, danehans commented
After resolving review feedback, `make generate-changelog` to generate a new changelog.

2025-01-13 21:46 UTC, nfuden commented
now in krt

2025-01-13 21:46 UTC, closed without merging